/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package WLVG_app.Ticketing;

import WLVG_app.Controller;
import javax.swing.JOptionPane;

/**
 *
 * @author eugene
 */
public class BuyTicketsPanel extends javax.swing.JPanel {

    private Controller cntl;

    /**
     * Creates new form BuyTicketsPanel
     */
    public BuyTicketsPanel(Controller control) {
        this.cntl = control;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        BuyTicketsPanel = new javax.swing.JLabel();
        LocationComboBox = new javax.swing.JComboBox<>();
        DateComboBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        QuantityComboBox = new javax.swing.JComboBox<>();
        goNextButton = new javax.swing.JButton();

        BuyTicketsPanel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        BuyTicketsPanel.setText("Purchase Tickets");

        jLabel2.setText("Location");

        jLabel3.setText("Date");

        jLabel4.setText("Quantity");

        goNextButton.setText("Next");
        goNextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goNextButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(148, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(BuyTicketsPanel)
                                                .addGap(69, 69, 69))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel4)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(QuantityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addComponent(jLabel3)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(DateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addComponent(jLabel2)
                                                        .addGap(53, 53, 53)
                                                        .addComponent(LocationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(goNextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(99, 99, 99)))
                                .addGap(127, 127, 127))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(BuyTicketsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(LocationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(DateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3))
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(QuantityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(45, 45, 45)
                                .addComponent(goNextButton)
                                .addContainerGap(213, Short.MAX_VALUE))
        );
    }// </editor-fold>                        

    private void goNextButtonActionPerformed(java.awt.event.ActionEvent evt) {
        if (String.valueOf(QuantityComboBox.getSelectedItem()).equals("0")) {
            JOptionPane.showMessageDialog(null, "You must purchase at least 1 ticket");
        } else {
            String date = (String) DateComboBox.getSelectedItem().toString();
            String location = (String) LocationComboBox.getSelectedItem().toString();
            int quantity = (int) QuantityComboBox.getSelectedItem();
            cntl.setTicketLocation(location);
            cntl.setTicketDate(date);
            cntl.setTicketQuantity(quantity);
            cntl.newPayment();
        }
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel BuyTicketsPanel;
    private javax.swing.JComboBox<String> DateComboBox;
    private javax.swing.JComboBox<String> LocationComboBox;
    private javax.swing.JComboBox<String> QuantityComboBox;
    private javax.swing.JButton goNextButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration                   

    /**
     * @return the BuyTicketsPanel
     */
    public javax.swing.JLabel getBuyTicketsPanel() {
        return BuyTicketsPanel;
    }

    /**
     * @return the DateComboBox
     */
    public javax.swing.JComboBox<String> getDateComboBox() {
        return DateComboBox;
    }

    /**
     * @return the LocationComboBox
     */
    public javax.swing.JComboBox<String> getLocationComboBox() {
        return LocationComboBox;
    }

    /**
     * @return the QuantityComboBox
     */
    public javax.swing.JComboBox<String> getQuantityComboBox() {
        return QuantityComboBox;
    }

    /**
     * @return the jButton1
     */
    public javax.swing.JButton getGoNextButton() {
        return goNextButton;
    }
}
