/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package WLVG_app.Payments;

import WLVG_app.Controller;
import com.google.gson.Gson;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author jackgallagher
 */
public class PaymentScreen extends javax.swing.JFrame {
    
    private Controller cntl;
    
    /** Creates new form PaymentScreen */
    public PaymentScreen(Controller control) {
        this.cntl = control;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        creditCard_JPanel = new javax.swing.JPanel();
        zipCodeField = new javax.swing.JTextField();
        lastNameField = new javax.swing.JTextField();
        firstNameField = new javax.swing.JTextField();
        expirationDateField = new javax.swing.JTextField();
        cardNumberField = new javax.swing.JTextField();
        firstNameLabel = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        securityCodeField = new javax.swing.JTextField();
        pageTitle = new javax.swing.JLabel();
        submitPaymentBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lastNameField.setToolTipText("");

        cardNumberField.setToolTipText("");

        firstNameLabel.setLabelFor(firstNameField);
        firstNameLabel.setText("First Name:");

        lastNameLabel.setText("Last Name:");

        jLabel3.setLabelFor(expirationDateField);
        jLabel3.setText("Expiration Date:");

        jLabel4.setLabelFor(cardNumberField);
        jLabel4.setText("Credit Card Number:");

        jLabel1.setLabelFor(zipCodeField);
        jLabel1.setText("Security Code:");

        jLabel5.setLabelFor(securityCodeField);
        jLabel5.setText("Zip Code:");

        pageTitle.setFont(new java.awt.Font("Malayalam MN", 0, 36)); // NOI18N
        pageTitle.setForeground(new java.awt.Color(205, 13, 12));
        pageTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pageTitle.setText("Payment Screen");

        submitPaymentBtn.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        submitPaymentBtn.setText("Submit Payment");
        submitPaymentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitPaymentBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout creditCard_JPanelLayout = new javax.swing.GroupLayout(creditCard_JPanel);
        creditCard_JPanel.setLayout(creditCard_JPanelLayout);
        creditCard_JPanelLayout.setHorizontalGroup(
            creditCard_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pageTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(creditCard_JPanelLayout.createSequentialGroup()
                .addGroup(creditCard_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(creditCard_JPanelLayout.createSequentialGroup()
                        .addGroup(creditCard_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(creditCard_JPanelLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(creditCard_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lastNameLabel)
                                    .addComponent(firstNameLabel)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(14, 14, 14))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, creditCard_JPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(creditCard_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(creditCard_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(securityCodeField, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                            .addComponent(firstNameField)
                            .addComponent(lastNameField)
                            .addComponent(expirationDateField)
                            .addComponent(cardNumberField)
                            .addComponent(zipCodeField)))
                    .addGroup(creditCard_JPanelLayout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(submitPaymentBtn)))
                .addContainerGap(244, Short.MAX_VALUE))
        );
        creditCard_JPanelLayout.setVerticalGroup(
            creditCard_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(creditCard_JPanelLayout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(pageTitle)
                .addGap(48, 48, 48)
                .addGroup(creditCard_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameLabel)
                    .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(creditCard_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(creditCard_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(expirationDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(creditCard_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cardNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(creditCard_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zipCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(creditCard_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(securityCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(43, 43, 43)
                .addComponent(submitPaymentBtn)
                .addGap(67, 67, 67))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(creditCard_JPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(creditCard_JPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitPaymentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitPaymentBtnActionPerformed
    
        BillingInfo bInfo = new BillingInfo();
        
        String firstName = firstNameField.getText();
        String lastName = lastNameField.getText();
        Double cardNumber = new Double(cardNumberField.getText());
        Integer expirationDate = new Integer(expirationDateField.getText());
        Integer securityCode = new Integer(securityCodeField.getText());
        Integer billingZipCode = new Integer(zipCodeField.getText());
        
        bInfo.setFirstName(firstName);
        bInfo.setLastName(lastName);
        bInfo.setCardNumber(cardNumber);
        bInfo.setExpirationDate(expirationDate);
        bInfo.setSecurityCode(securityCode);
        bInfo.setBillingZipCode(billingZipCode);
     
        Gson gson = new Gson();
        
        try (FileWriter writer = new FileWriter("billinginfo.json")) {
            gson.toJson(bInfo, writer);   
        } catch (IOException e) {
            e.printStackTrace();
        }
        
        
        
        
        System.out.println(firstName);
        System.out.println(lastName);
        System.out.println(cardNumber);
        System.out.println(expirationDate);
        System.out.println(securityCode);
        System.out.println(billingZipCode);
        
        
        JOptionPane.showMessageDialog(null, "Thanks for your purchase! See you soon at WallyLand!");
        setVisible(false); //you can't see me!
        this.cntl.paymentDone();
        dispose(); //Destroy the JFrame object
    }//GEN-LAST:event_submitPaymentBtnActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField cardNumberField;
    private javax.swing.JPanel creditCard_JPanel;
    private javax.swing.JTextField expirationDateField;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public javax.swing.JTextField lastNameField;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JLabel pageTitle;
    public javax.swing.JTextField securityCodeField;
    public javax.swing.JButton submitPaymentBtn;
    public javax.swing.JTextField zipCodeField;
    // End of variables declaration//GEN-END:variables

    public JTextField getCardNumberField() {
        return cardNumberField;
    }

    public JTextField getExpirationDateField() {
        return expirationDateField;
    }

    public JTextField getFirstNameField() {
        return firstNameField;
    }

    public JTextField getLastNameField() {
        return lastNameField;
    }

    public JTextField getSecurityCodeTxtField() {
        return zipCodeField;
    }

    public JTextField getZipcodeTxtField() {
        return securityCodeField;
    }

}
