/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package WLVG_app.Login;

import WLVG_app.Controller;

/**
 *
 * @author jack
 */
public class NavigationPanel extends javax.swing.JPanel {

    /**
     * Creates new form NavigationPage
     */
    private Controller cntl;
    
    public NavigationPanel(Controller control) {
        this.cntl = control;
        initComponents();
    }

    public NavigationPanel() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        hotelBtn2 = new javax.swing.JButton();
        foodBtn2 = new javax.swing.JButton();
        timesBtn2 = new javax.swing.JButton();
        ticketsBtn2 = new javax.swing.JButton();

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 34)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Welcome to the WallyLand Application!");

        hotelBtn2.setText("Book a Hotel");
        hotelBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hotelBtn2ActionPerformed(evt);
            }
        });

        foodBtn2.setText("Order Food");
        foodBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foodBtn2ActionPerformed(evt);
            }
        });

        timesBtn2.setText("View Wait Times");
        timesBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timesBtn2ActionPerformed(evt);
            }
        });

        ticketsBtn2.setText("Buy Tickets");
        ticketsBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ticketsBtn2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 642, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ticketsBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timesBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(foodBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hotelBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(258, 258, 258))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(hotelBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(foodBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(timesBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ticketsBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void hotelBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hotelBtn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hotelBtn2ActionPerformed

    private void foodBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foodBtn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_foodBtn2ActionPerformed

    private void timesBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timesBtn2ActionPerformed
        this.removeAll();
        cntl.switchToWaitTimes();
    }//GEN-LAST:event_timesBtn2ActionPerformed

    private void ticketsBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ticketsBtn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ticketsBtn2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton foodBtn;
    public javax.swing.JButton foodBtn1;
    public javax.swing.JButton foodBtn2;
    public javax.swing.JButton hotelBtn;
    public javax.swing.JButton hotelBtn1;
    public javax.swing.JButton hotelBtn2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JButton ticketsBtn;
    public javax.swing.JButton ticketsBtn1;
    public javax.swing.JButton ticketsBtn2;
    public javax.swing.JButton timesBtn;
    public javax.swing.JButton timesBtn1;
    public javax.swing.JButton timesBtn2;
    // End of variables declaration//GEN-END:variables
}
